// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {nvapi} from '../models';

export function AddGameManually():Promise<models.Game>;

export function CheckAppUpdate():Promise<main.AppUpdateInfo>;

export function DeleteCachedVersion(arg1:string):Promise<void>;

export function DownloadOfficialDLL(arg1:models.DLLRecord):Promise<void>;

export function FetchSwapperManifest():Promise<models.SwapperManifest>;

export function GetComponentStatus():Promise<main.ComponentStatus>;

export function GetConfig():Promise<models.AppConfiguration>;

export function GetDownloadedVersions():Promise<Array<string>>;

export function GetGPU():Promise<main.GpuResult>;

export function GetGame(arg1:number):Promise<models.Game>;

export function GetGames():Promise<Array<models.Game>>;

export function GetNVAPIPresets(arg1:string):Promise<nvapi.PresetResult>;

export function InstallOptiScaler(arg1:number,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<main.InstallResult>;

export function LaunchGame(arg1:number):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveGame(arg1:string):Promise<void>;

export function RestoreOfficialDLL(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:models.AppConfiguration):Promise<void>;

export function ScanGames():Promise<Array<models.Game>>;

export function SetNVAPIPreset(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SwapOfficialDLL(arg1:models.DLLRecord,arg2:string):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<boolean>;

export function UninstallOptiScaler(arg1:number):Promise<main.InstallResult>;
