// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameManually() {
  return window['go']['main']['App']['AddGameManually']();
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function DeleteCachedVersion(arg1) {
  return window['go']['main']['App']['DeleteCachedVersion'](arg1);
}

export function DownloadOfficialDLL(arg1) {
  return window['go']['main']['App']['DownloadOfficialDLL'](arg1);
}

export function FetchSwapperManifest() {
  return window['go']['main']['App']['FetchSwapperManifest']();
}

export function GetComponentStatus() {
  return window['go']['main']['App']['GetComponentStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadedVersions() {
  return window['go']['main']['App']['GetDownloadedVersions']();
}

export function GetGPU() {
  return window['go']['main']['App']['GetGPU']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetNVAPIPresets(arg1) {
  return window['go']['main']['App']['GetNVAPIPresets'](arg1);
}

export function InstallOptiScaler(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallOptiScaler'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RemoveGame(arg1) {
  return window['go']['main']['App']['RemoveGame'](arg1);
}

export function RestoreOfficialDLL(arg1, arg2) {
  return window['go']['main']['App']['RestoreOfficialDLL'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanGames() {
  return window['go']['main']['App']['ScanGames']();
}

export function SetNVAPIPreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNVAPIPreset'](arg1, arg2, arg3);
}

export function SwapOfficialDLL(arg1, arg2) {
  return window['go']['main']['App']['SwapOfficialDLL'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UninstallOptiScaler(arg1) {
  return window['go']['main']['App']['UninstallOptiScaler'](arg1);
}
